### PR TITLE
Improve logging

### PR DESCRIPTION
**Pull request by doskabouter**

### CODE REVIEW

**Comment by damienhaynes** [comment]
Hi @doskabouter , would you like to resolve the conflict for this.

**Comment by doskabouter** [comment]
Done. Perhaps you can do something more with this error instead of just logging (f.e. show to the user, or remove the entry from the list of movies?)

**Comment by damienhaynes** [comment]
Looks good. 

With respect to you comment regarding doing something when there is an error...I believe there is some code which checks the return result of UpdateMediaInfo() and pops up a dialog if scanning in Configuration manually (not 100% sure on this as would require closer analysis).

Having said that, shouldn't we check the stream counts before attempting to get the individual properties and return error ?

fyi, the filters in the MovPics configuration Movie Manager pane allows you to filter movies with missing MediaInfo, this can be useful in rescanning movies which failed MI retrieval.

**Comment by doskabouter** [comment]
I didn't get any popups for my corrupt file, and it used to have mediainfo (when I first scanned it a long time ago it wasn't corrupt), so filters were no use for me.
But as this is really a corner-case, I don't think any changes are really necessary...

**Pull request merged**
